plugins {
    id 'java'
    id 'org.springframework.boot' version '3.4.2'
    id 'io.spring.dependency-management' version '1.1.7'
}

group = 'com.motnip'
version = '0.0.1-SNAPSHOT'

java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(17)
    }
}

configurations {
    compileOnly {
        extendsFrom annotationProcessor
    }
}

repositories {
    mavenCentral()
}

dependencies {
    implementation 'org.springframework.boot:spring-boot-starter-actuator'
    implementation 'org.springframework.boot:spring-boot-starter-data-jpa'
    implementation 'org.springframework.boot:spring-boot-starter-web'
    implementation 'org.springframework.boot:spring-boot-starter-validation'
    implementation 'org.springframework.boot:spring-boot-starter-logging'
    implementation 'org.springdoc:springdoc-openapi-starter-webmvc-ui:2.8.9'
    //implementation 'org.hibernate:hibernate-jpamodelgen:7.1.1.Final'
    //implementation 'org.springframework.boot:spring-boot-hibernate:4.0.0-M3'


    //implementation 'org.hibernate.orm:hibernate-core:7.1.1.Final'


    compileOnly 'org.projectlombok:lombok'
    //annotationProcessor 'org.hibernate.orm:hibernate-processor:7.1.1.Final'
    annotationProcessor 'org.hibernate:hibernate-jpamodelgen:6.4.4.Final'
    annotationProcessor 'org.projectlombok:lombok'
    runtimeOnly 'org.postgresql:postgresql'
    testImplementation 'org.springframework.boot:spring-boot-starter-test'
    testImplementation 'org.springframework.boot:spring-boot-test'
    testImplementation 'org.springframework.boot:spring-boot-testcontainers'
    testImplementation 'org.testcontainers:junit-jupiter'
    testImplementation 'org.testcontainers:postgresql'
    testRuntimeOnly 'org.junit.platform:junit-platform-launcher'
}

tasks.named('test') {
    useJUnitPlatform()
}

compileJava {
    options.annotationProcessorPath = configurations.annotationProcessor
}

sourceSets {
    generated {
        java.srcDir "${buildDir}/generated/src/java/"
    }
}

tasks.withType(JavaCompile) {
    options.compilerArgs += ['-AaddGenerationDate=true']
}
