spring.jpa.show-sql=true
spring.jpa.hibernate.show-sql=true


spring.jpa.properties.hibernate.dialect = org.hibernate.dialect.PostgreSQLDialect
spring.datasource.url=jdbc:postgresql://localhost:5432/jobapp-db
spring.datasource.username=jobapp-admin
spring.datasource.password=tomas0584!
#always initialize a database using scripts, at the moment it stays here we can move it to tes env
spring.sql.init.mode=never
spring.jpa.generate-ddl=true
#Drive by Hibernate for creating database table and puts data
#spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.hibernate.ddl-auto=update
#script-based DataSource initialization to be able to build upon the schema creation by Hibernate
spring.datasource.initialize=false
spring.jpa.defer-datasource-initialization=false

