spring.jpa.properties.hibernate.dialect = org.hibernate.dialect.PostgreSQLDialect
spring.datasource.url=jdbc:postgresql://localhost:5432/jobapp-db
spring.datasource.username=jobapp-admin
spring.datasource.password=tomas0584!

#init database
#Drive by Hibernate for creating database table and puts data
spring.jpa.hibernate.ddl-auto=create-drop
spring.sql.init.mode=always
spring.jpa.generate-ddl=true
#script-based DataSource initialization to be able to build upon the schema creation by Hibernate
#spring.datasource.initialize=true
#spring.jpa.properties.hibernate.hbm2ddl.import_files=init-db.sql
#spring.jpa.show-sql=true
#Pretty print
spring.jpa.properties.hibernate.format_sql=true

# Logging SQL
logging.level.org.hibernate.SQL=DEBUG
# Show bound parameter values
logging.level.org.hibernate.orm.jdbc.bind=TRACE
# Optional: show extracted column values from ResultSets
logging.level.org.hibernate.orm.jdbc.extract=TRACE
# (Optional) also echo SQL to the console (separate from logging)
hibernate.format_sql=true